name: solr-query
version: 0.4.0
synopsis: Solr query EDSL
description: A typed Solr query EDSL.
category: DSLs
author: Mitchell Rosen
maintainer: mitchellwrosen@gmail.com
github: Sentenai/solr-query
license: BSD3
copyright: 2016 Sentenai, Inc.

ghc-options: -Wall

default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - StandaloneDeriving
  - TypeFamilies

dependencies:
  - base        >= 4.7     && < 5
  - base-compat >= 0.9.1
  - data-default-class
  - old-locale                < 1.1
  - semigroups  >= 0.3     && < 0.19
  - text        >= 1.0     && < 1.3
  - time        >= 1.1.2.0 && < 1.7

library:
  source-dirs: src
  other-modules:
    - Builder
    - Solr.Prelude
    - Solr.Query.Filter.Internal
    - Solr.Query.Internal.Internal
    - Solr.Query.Lucene.Expr
    - Solr.Query.Lucene.Expr.Type
    - Solr.Query.Lucene.Internal.Internal
    - Solr.Query.Param

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - hspec
      - solr-query
