name: solr-query
version: 0.3.5.0
synopsis: Solr query EDSL
description: Solr query EDSL
category: DSLs
author: Sentenai, Inc.
maintainer: mitchellwrosen@gmail.com
github: Sentenai/solr-query
license: BSD3
copyright: 2016 Sentenai, Inc.

ghc-options: -Wall

dependencies:
  - base       >= 4      && < 5
  - bytestring >= 0.10.4 && < 0.11
  - semigroups >= 0.3    && < 0.19
  - text       >= 1.0    && < 1.3

library:
  source-dirs: src
  other-modules:
    - Builder
    - Solr.Expr.Initial.Untyped.Internal
    - Solr.Expr.Internal
    - Solr.Query.Initial.Internal

  dependencies:
    - bytestring-show >= 0.2 && < 0.4
    - uniplate        >= 1.3 && < 1.7

tests:
  spec:
    main: test/Spec.hs
    dependencies:
      - hspec
      - solr-query

  doctest:
    main: test/DocTest.hs
    dependencies:
      - doctest >= 0.11
      - solr-query
