name: solr-query
version: 0.3.6.0
synopsis: Solr query EDSL
description: Solr query EDSL
category: DSLs
author: Sentenai, Inc.
maintainer: mitchellwrosen@gmail.com
github: Sentenai/solr-query
license: BSD3
copyright: 2016 Sentenai, Inc.

ghc-options: -Wall

default-extensions:
  - DataKinds
  - DeriveFunctor
  - ExistentialQuantification
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeFamilies
  - TypeOperators

dependencies:
  - base       >= 4      && < 5
  - bytestring >= 0.10.4 && < 0.11
  - semigroups >= 0.3    && < 0.19
  - text       >= 1.0    && < 1.3

library:
  source-dirs: src
  other-modules:
    - Builder
    - Solr.Expr.Internal
    - Solr.Query.Param.Internal
  dependencies:
    - bytestring-show >= 0.2 && < 0.4
    - constraints     >= 0.6 && < 0.9
    - uniplate        >= 1.3 && < 1.7

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - hspec
      - mtl
      - QuickCheck
      - solr-query
      - uniplate

  doctest:
    main: test/DocTest.hs
    dependencies:
      - doctest >= 0.11
      - solr-query
