name: solr-query
version: 0.3.4.0
synopsis: Solr query EDSL
description: Solr query EDSL
category: DSLs
author: Sentenai, Inc.
maintainer: mitchellwrosen@gmail.com
github: Sentenai/solr-query
license: BSD3
copyright: 2016 Sentenai, Inc.

ghc-options: -Wall

dependencies:
  - base       >= 4    && < 5
  - bytestring >= 0.10 && < 0.11
  - semigroups >= 0.3  && < 0.19
  - text       >= 1.0  && < 1.3

library:
  source-dirs: src

tests:
  spec:
    main: test/Spec.hs
    dependencies:
      - hspec
      - solr-query
