name: solr-query
version: 0.3.6.0
synopsis: Solr query EDSL
description: A typed, finally tagless Solr query EDSL.
category: DSLs
author: Mitchell Rosen
maintainer: mitchellwrosen@gmail.com
github: Sentenai/solr-query
license: BSD3
copyright: 2016 Sentenai, Inc.

flags:
  with-constraints:
    description: Depend on constraints
    default: False
    manual: False

ghc-options: -Wall

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeFamilies
  - TypeOperators

dependencies:
  - base       >= 4.7     && < 5
  - old-locale               < 1.1
  - semigroups >= 0.3     && < 0.19
  - text       >= 1.0     && < 1.3
  - time       >= 1.1.2.0 && < 1.7

library:
  source-dirs: src
  other-modules:
    - Builder
    - Solr.Expr.Class
    - Solr.Expr.Impl.Final
    - Solr.Expr.Impl.Initial.Typed
    - Solr.Expr.Impl.Initial.Untyped
    - Solr.Expr.Type
    - Solr.Prelude
    - Solr.Query.Class
    - Solr.Query.Impl.Final
    - Solr.Query.Impl.Initial
    - Solr.Query.LocalParam
    - Solr.Query.Param
  dependencies:
    - uniplate >= 1.3 && < 1.7
  when:
    condition: flag(with-constraints)
    cpp-options: -DWITH_CONSTRAINTS
    dependencies:
      - constraints >= 0.6 && < 0.9

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - hspec
      - mtl
      - QuickCheck
      - quickcheck-instances
      - solr-query
      - uniplate

  doctest:
    main: test/DocTest.hs
    dependencies:
      - doctest >= 0.11
      - solr-query
