name: solr-query
version: 0.3.3.0
synopsis: Solr query EDSL
description: Solr query EDSL
author: Sentenai, Inc.
github: Sentenai/solr-query
license: BSD3
copyright: 2016 Sentenai, Inc.

ghc-options: -Wall

dependencies:
  - base
  - bytestring < 0.11
  - text       > 1.0 && < 1.3

library:
  source-dirs: src
